### ISSUE TITLE
A way to return the best action?

### ISSUE THREAD

**Issue by deepdatadive** [DenseLance/mcts-simple#1]
All your tutorials and examples always utilize the self_play() method. Is there a way to just return the best possible action instead of completing the game?

**Comment by DenseLance** [comment]
The only way you can infer the best action being made during self-play is through the `Game.render()` method based on the game state that is being output. Alternatively, you can manually call `Node.choose_best_action()` for the current node to retrieve the best possible action.

Moreover, Step 5 of the TicTacToe example gives an idea on how we can manually run the game, and since it is separate from the `MCTS.self_play()` method, we can stop the game at any point in time and return the evaluations of the actions that can be taken. The example also shows the use of `Node.choose_best_action()`.

Does this answer your question?

**Comment by DenseLance** [comment]
Issue closed due to inactivity.

**Comment by DenseLance** [comment]
Issue closed due to inactivity.
